# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "28564bf45a0287c8a9e6c4e46a0df75e"
name = "admin-gpt"
handle = "admin-gpt-2"
application_url = "https://0ea8-49-207-244-45.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "palash-test-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://0ea8-49-207-244-45.ngrok-free.app/auth/callback",
  "https://0ea8-49-207-244-45.ngrok-free.app/auth/shopify/callback",
  "https://0ea8-49-207-244-45.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
